In [2]:
# importing the required packages
import sys
import numpy as np

In [4]:
# Basic Numpy Arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# displaying the summation of the first elements of the arrays
print("Sum of first 2 elements: ", (a[0] + b[0]))

Sum of first 2 elements:  6


In [7]:
# summation of all the corresponding elements of both the arrays

print("Summation of corresponding elements is: ")
for i in range(len(a)):
    print(a[i] + b[i], end=" ")

Summation of corresponding elements is: 
6 8 10 12 

In [8]:
# slicing the numpy array (viewing the sub-array)
lowerbound = int(input("Enter the lowerbound: "))
upperbound = int(input("Enter the upperbound: "))

# displaying the sub-array
print("The elements between index", lowerbound, "and index", upperbound, "is:",
     a[lowerbound:upperbound])

Enter the lowerbound: 1
Enter the upperbound: 4
The elements between index 1 and index 4 is: [2 3 4]


In [12]:
# checking the type of the array that we are trying to store

# creating a different array other than the 2 that were created before
number_of_elements = int(input("Enter the array length: "))
print("Enter the elements of the array one by one... ")
empty_list = list()

for i in range(number_of_elements):
    empty_list.append(int(input()))
    
created_array = np.array(empty_list)  

# viewing the array and checking its type
print("Data-Type of", created_array, "is:", (created_array.dtype))


Enter the array length: 4
Enter the elements of the array one by one... 
1
2
3
4
Data-Type of [1 2 3 4] is: int64


In [13]:
# creating a numpy array with explicitly mentioning the target datatype

number_of_elements = int(input("Enter the array length: "))
print("Enter the elements of the array one by one... ")
empty_list = list()

for i in range(number_of_elements):
    empty_list.append(int(input()))
    
created_array1 = np.array(empty_list, dtype=np.float)

# visualizing the created array
print("Array created:", created_array1)

Enter the array length: 5
Enter the elements of the array one by one... 
3
1
6
2
9
Array created: [3. 1. 6. 2. 9.]


In [17]:
# creating multi-dimensional arrays using NumPy

list1, list2 = list(), list()
number1 = int(input("Enter length of 1st list: "))
number2 = int(input("Enter length of 2nd list: "))

print("Enter elements of 1st list one by one... ")
for i in range(number1):
    list1.append(int(input()))
    
print("Enter elements of 2nd list one by one...")
for j in range(number2):
    list2.append(int(input()))

# creation of the 2-D array
multidimensional_array = np.array([list1, list2])

# viewing the 2-D array
print("2-D array is:")
print(multidimensional_array)

# checking the shape of the created array
print("Shape of the array:", multidimensional_array.shape)

# checking the dimensions of the created array
print("Dimension of the array:", multidimensional_array.ndim)

# checking the size of the created array
print("Size of the array:", multidimensional_array.size)

Enter length of 1st list: 4
Enter length of 2nd list: 4
Enter elements of 1st list one by one... 
1
2
3
4
Enter elements of 2nd list one by one...
5
6
7
8
2-D array is:
[[1 2 3 4]
 [5 6 7 8]]
Shape of the array: (2, 4)
Dimension of the array: 2
Size of the array: 8


In [25]:
# Indexing and Slicing of Matrices

# creating a SQUARE MATRIX by giving the elements manually
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# displaying the created matrix
print("Matrix created is as follows:- \n")
print(matrix,"\n")

# extracting the rows of the matrix
print("First row of the matrix:", matrix[0])
print("Second row of the matrix:", matrix[1])
print("Third row of the matrix:", matrix[2])
print("Fourth row of the matrix:", matrix[3])

# displaying an element of a particular row and column in the matrix
row_no = int(input("Enter the row number:"))
col_no = int(input("Enter the column number:"))
print("Element at (", row_no,",", col_no,") is:", matrix[row_no][col_no])

# displaying the sub-matrix with all the rows and selected columns
#starting_col_no = int(input("Enter starting column: "))
ending_col_no = int(input("Enter ending column: "))
print("The submatrix is as displayed below:\n")
print(matrix[:, :ending_col_no])

Matrix created is as follows:- 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

First row of the matrix: [1 2 3 4]
Second row of the matrix: [5 6 7 8]
Third row of the matrix: [ 9 10 11 12]
Fourth row of the matrix: [13 14 15 16]
Enter the row number:2
Enter the column number:3
Element at ( 2 , 3 ) is: 12
Enter ending column: 2
The submatrix is as displayed below:

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [26]:
# modification of a particular row of the matrix

# displaying the original matrix
print("Original Matrix:\n")
print(matrix)
print() # for inserting a new-line

row_number = int(input("Enter the row number to be modified: "))
new_elements = list()

number_of_elements = int(input("Enter the number of elements: "))
print("Enter the new elements of the row...")
for i in range(number_of_elements):
    new_elements.append(int(input()))
    
# setting the row of the matrix with the new elements
matrix[row_number] = np.array(new_elements)

# displaying the modified matrix
print() # for inserting a new-line
print("Modified Matrix is:\n")
print(matrix)

Original Matrix:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Enter the row number to be modified: 3
Enter the number of elements: 4
Enter the new elements of the row...
0
0
0
0

Modified Matrix is:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 0  0  0  0]]


In [28]:
# displaying the SUMMARY STATISTICS of the matrix

# in this section, we will be diplaying the values
# of different statistical measures of the elements
# of the matrix

# displaying the SUM of the elements of the matrix
print("Sum of the elements:", matrix.sum())

# displaying the MEAN of the elements of the matrix
print("Mean/Average of the elements:", matrix.mean())

# displaying the STANDARD DEVIATION of the elements of the matrix
print("Standard Deviation of the elements:", matrix.std())

# displaying the VARIANCE of the elements of the matrix
print("Variance of the elements:", matrix.var())

Sum of the elements: 78
Mean/Average of the elements: 4.875
Standard Deviation of the elements: 4.106016926414211
Variance of the elements: 16.859375


In [34]:
# BROADCASTING and VECTORIZED operations

# using the arange() function
value_of_range = int(input("Enter the upperbound of the range:"))
sample_array = np.arange(value_of_range)

# displaying the created array
print("Created Array:", sample_array)

# broadcasting a single operation through all the elements of the array
number = int(input("Enter a value: "))

# 1. Broadcasting ADDITION
print("After BROADCASTED ADDITION, array is:", (sample_array + number))

# 2. Broadcasting SUBTRACTION
print("After BROADCASTED SUBTRACTION, array is:", (sample_array - number))

# 3. Broadcasting MULTIPLICATION
print("After BROADCASTED MULTIPLICATION, array is:", (sample_array * number))

# 4. Broadcasting DIVISION
print("After BROADCASTED DIVISION, array is:", (sample_array // number))

# 5. Broadcasting EXPONENTIATION
print("After BROADCASTED EXPONENTIATION, array is:", (sample_array ** number))

Enter the upperbound of the range:10
Created Array: [0 1 2 3 4 5 6 7 8 9]
Enter a value: 5
After BROADCASTED ADDITION, array is: [ 5  6  7  8  9 10 11 12 13 14]
After BROADCASTED SUBTRACTION, array is: [-5 -4 -3 -2 -1  0  1  2  3  4]
After BROADCASTED MULTIPLICATION, array is: [ 0  5 10 15 20 25 30 35 40 45]
After BROADCASTED DIVISION, array is: [0 0 0 0 0 1 1 1 1 1]
After BROADCASTED EXPONENTIATION, array is: [    0     1    32   243  1024  3125  7776 16807 32768 59049]


In [36]:
# operations between two arrays

first_array = np.array([1, 2, 3, 4, 5])
second_array = np.array([6, 7, 8, 9, 10])

# 1. Performing ADDITION
print("After ADDITION:", (first_array + second_array))

# 2. Performing SUBTRACTION
print("After SUBTRACTION:", (first_array - second_array))

# 3. Performing MULTIPLICATION
print("After MULTIPLICATION:", (first_array * second_array))

# 4. Performing DIVISION
print("After DIVISION:", (second_array // first_array))

#5. Performing EXPONENTIATION
print("After EXPONENTIATION:", (first_array ** second_array))

After ADDITION: [ 7  9 11 13 15]
After SUBTRACTION: [-5 -5 -5 -5 -5]
After MULTIPLICATION: [ 6 14 24 36 50]
After DIVISION: [6 3 2 2 2]
After EXPONENTIATION: [      1     128    6561  262144 9765625]


In [3]:
# BOOLEAN ARRAYS

# 1. selecting specific elements from an array by traditional Python method
my_array = np.array([1, 2, 3, 4, 5])
number_of_elements = int(input("Enter no. of elements you want to extract:"))
index_list = list()
extracted_elements_list = list()

print("Enter the indexes:")
for i in range(number_of_elements):
    index_list.append(int(input()))
    
for j in index_list:
    extracted_elements_list.append(my_array[j])
    
print("The elements extracted are:", extracted_elements_list)

# 2. extracting the elements by Boolean Array technique
# suppose the user wants to extract 2 elements from the array


Enter no. of elements you want to extract:2
Enter the indexes:
1
4
The elements extracted are: [2, 5]


In [9]:
# LINEAR ALGEBRA on NumPy matrices

# taking the first matrix
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# displaying the shape
print("Shape of Matrix1:", matrix1.shape)

# taking the second matrix
matrix2 = np.array([[11, 12],
                    [13, 14],
                    [15, 16]])

# displaying the shape
print("Shape of Matrix2:", matrix2.shape)

# 1. Performing DOT PRODUCT between the two matrices

print("Dot product between Matrix1 and Matrix2 is:- \n")
print(matrix1.dot(matrix2), "\n")

# 2. Performing CROSS PRODUCT between the two matrices

print("Cross product between Matrix1 and Matrix2 is:- \n")
print(matrix1 @ matrix2)

Shape of Matrix1: (3, 3)
Shape of Matrix2: (3, 2)
Dot product between Matrix1 and Matrix2 is:- 

[[ 82  88]
 [199 214]
 [316 340]]
Cross product between Matrix1 and Matrix2 is:- 

[[ 82  88]
 [199 214]
 [316 340]]


In [14]:
# Size of objects in memory

number = int(input("Enter any number: "))
print("Size of", number, "in Bytes:", sys.getsizeof(number), "\n")

# Comparison of TIME REQUIREMENT of computations

# 1. Simple Python approach
# ------------------------------------------------

# creating a list containing 1st 1000 integers
my_list = list(range(1000))

# performing the operation and finding out the time
%time sum([i ** 2 for i in my_list])

# 2. NumPy approach
# -----------------------------------------------

# creating a numpy array containing the first 1000 integers
my_array = np.arange(1000)

# performing the same operation and finding out the time
%time np.sum(my_array ** 2)

Enter any number: 2
Size of 2 in Bytes: 28 

CPU times: user 570 µs, sys: 173 µs, total: 743 µs
Wall time: 751 µs
CPU times: user 1.73 ms, sys: 48 µs, total: 1.78 ms
Wall time: 214 ms


332833500